import assert from 'node:assert/strict';
import fs from 'node:fs';

const controls = fs.readFileSync('public/scripts/animated-qr-controls.js', 'utf8');
const awake = fs.readFileSync('public/scripts/animated-qr-screen-awake.js', 'utf8');
const qrHelper = fs.readFileSync('public/scripts/qr-helper.js', 'utf8');
const index = fs.readFileSync('public/index.html', 'utf8');
const mainCss = fs.readFileSync('public/styles/styles-main.css', 'utf8');
const deferredCss = fs.readFileSync('public/styles/styles-deferred.css', 'utf8');

assert.match(controls, /#animated-qr-send-dialog #qr-send-canvas-container\{?/);
assert.match(controls, /width:min\(360px,calc\(100% - 16px\),calc\(100vw - 48px\),calc\(100dvh - 300px\)\)!important/);
assert.match(controls, /max-width:100%!important/);
assert.match(controls, /min-width:0!important/);
assert.match(controls, /min-width:0!important;\s*min-height:0!important/);
assert.match(controls, /@media\(max-width:600px\)/);
assert.match(controls, /@media\(max-height:700px\)/);
assert.match(controls, /position:relative;\s*z-index:3;\s*isolation:isolate/);
assert.match(controls, /overflow:visible!important/);
assert.match(controls, /height:auto!important/);
assert.match(controls, /aspect-ratio:1 \/ 1/);
assert.match(controls, /overflow:visible!important/);

assert.match(awake, /--text-color/);
assert.match(awake, /--bg-color-secondary/);
assert.match(awake, /var\(--primary-color\)/);
assert.match(awake, /prefers-color-scheme:dark/);
assert.match(awake, /#\$\{BUTTON_ID\}\[hidden\]/);
assert.match(awake, /aria-pressed/);
assert.match(awake, /Não desligar Tela \(Clique aqui\)/);
assert.match(awake, /Screen always on: Enabled/);
assert.match(awake, /isKeepScreenOnEnabled/);
assert.match(awake, /const hidden = !!android\(\) \|\| !isSupported\(\)/);
assert.match(awake, /button.textContent !== label/);
assert.match(awake, /button.hasAttribute\('title'\)/);
assert.match(awake, /if \(record.type === 'childList'\)/);
assert.match(awake, /if \(android\(\)\) \{/);
assert.match(awake, /btn btn-rounded btn-dark/);

assert.match(index, /id="qr-send-canvas-container"/);
assert.match(index, /id="qr-send-active-view"[^>]*hidden/);
assert.match(index, /<div class="hr-note">\s*<hr>\s*<div>\s*<span data-i18n-key="dialogs\.hr-or" data-i18n-attrs="text">OU<\/span>/);
assert.match(controls, /#animated-qr-send-dialog #qr-send-active-view\.row\.center,[\s\S]*?align-items:\s*stretch;[\s\S]*?justify-content:\s*flex-start;/);
assert.match(controls, /#animated-qr-send-dialog #qr-send-canvas-container\.layout-1[\s\S]*?height:\s*auto\s*!important;[\s\S]*?aspect-ratio:\s*1 \/ 1;/);
assert.match(controls, /background:\s*var\(--dialog-bg-color,\s*#fff\)/);
assert.doesNotMatch(controls, /background:var\(--paper-color,var\(--background-color,#fff\)\)/);
assert.match(mainCss, /#animated-qr-main-dialog \.erikraft-qr-card-send,[\s\S]*?box-sizing:\s*border-box;/);
assert.match(mainCss, /padding:\s*16px clamp\(16px, 4vw, 24px\)/);
assert.match(mainCss, /\.erikraft-qr-card-send > \.row\.gap-2\.fw\.center\.wrap > \.btn[\s\S]*?flex:\s*1 1 130px/);
assert.match(mainCss, /\.erikraft-qr-dialog \.erikraft-qr-paper > \.row\.center \{[\s\S]*?color:\s*rgb\(var\(--text-color\)\)/);
assert.match(mainCss, /\.erikraft-qr-dialog \.erikraft-qr-paper \{[\s\S]*?background-color:\s*var\(--dialog-bg-color\)/);
assert.match(mainCss, /\.erikraft-qr-dialog \.erikraft-qr-paper > \.row\.center:has\(\.dialog-title\)[\s\S]*?background-color:\s*var\(--accent-color,\s*var\(--primary-color\)\)/);
assert.match(mainCss, /\.erikraft-qr-dialog \.erikraft-qr-paper > \.row\.center:has\(\.dialog-title\) \.dialog-title \{[\s\S]*?color:\s*white/i);
assert.match(qrHelper, /Wait for the shared brand asset before the first non-animated QR render/);
assert.match(qrHelper, /!isAnimatedTransfer && !options\._logoReady && !this\._logoState\.available/);
assert.match(qrHelper, /return this\._ensureLogoLoaded\(logoPath\)\.then\(/);
assert.match(deferredCss, /\.hr-note > div \{[\s\S]*?display:\s*flex;[\s\S]*?justify-content:\s*center;/);
assert.doesNotMatch(index, /optical-matrix/);

console.log('Animated QR responsive/theme static checks passed.');
