import assert from 'node:assert/strict';
import fs from 'node:fs';

const source = fs.readFileSync('public/scripts/page-agent-ai.js', 'utf8');

assert.match(source, /PAGE_AGENT_EXT\.execute/);
assert.match(source, /createDialog/);
assert.match(source, /customInstructionDialog/);
assert.match(source, /promptConfig/);
assert.match(source, /PageAgentExtUserAuthToken/);
assert.match(source, /sessionApiKey/);
assert.doesNotMatch(source, /sessionStorage\.getItem\(SESSION_KEY\)/);
assert.doesNotMatch(source, /sessionStorage\.setItem\(SESSION_KEY/);
assert.doesNotMatch(source, /value: getApiKey\(\)/);
assert.match(source, /chromewebstore\.google\.com\/detail\/page-agent-ext/);
assert.match(source, /positionMenu/);
assert.match(source, /maxHeight/);
assert.match(source, /is-fullscreen/);
assert.match(source, /ai\.fullscreen/);
assert.match(source, /ai\.exit-fullscreen/);
assert.doesNotMatch(source, /window\.prompt/);
assert.doesNotMatch(source, /ai\.improve/);
assert.doesNotMatch(source, /ai\.correct/);
assert.doesNotMatch(source, /ai\.polish/);
assert.doesNotMatch(source, /ai\.code/);

assert.match(source, /data-erikraft-page-agent-target/);
assert.match(source, /Deixe em branco para manter a chave desta sessão/);
console.log('Page Agent dialog/responsive/security static checks passed.');

assert.match(source, /CDN_BOOKMARKLET/);
assert.doesNotMatch(source, /Descreva exatamente o que o Page Agent deve fazer/);
assert.doesNotMatch(source, /Ex\.: deixe o texto mais profissional, mas preserve o significado\./);
assert.doesNotMatch(source, /O Page Agent será limitado ao campo marcado no ErikrafT Drop™\./);
assert.doesNotMatch(source, /Parar tarefa atual/);
assert.match(source, /drag\.textContent = '✨PageAgent'/);
assert.match(source, /drag\.setAttribute\('aria-label', label \+ ': ✨PageAgent'\)/);
assert.match(source, /drag\.title = '✨PageAgent'/);
assert.match(source, /draggable = true/);
assert.match(source, /quick-run-title/);
assert.match(source, /quick-run-mirror/);
assert.match(source, /quick-run-cdn/);
assert.match(source, /bookmarklet-use/);
assert.match(source, /background-color:var\\(--dialog-bg-color\\)/);
assert.doesNotMatch(source, /navigator\\.clipboard\\.writeText/);
assert.doesNotMatch(source, /ai\\.copy/);
assert.match(source, /MIRROR_BOOKMARKLET/);
assert.match(source, /data-context="send-text"/);
assert.match(source, /prefers-color-scheme/);
assert.doesNotMatch(source, /rgb\\(var\\(--dialog-bg-color\\)\\)/);
assert.match(source, /var\\(--dialog-bg-color\\)/);
assert.match(source, /var\\(--bg-color-secondary\\)/);
assert.match(source, /appearance:none/);
assert.match(source, /-webkit-appearance:none/);
assert.match(source, /\.erikraft-page-agent-dialog__secondary \{/);
assert.match(source, /useBookmarklet/);
assert.match(source, /ai\\.use/);
assert.match(source, /ai\\.bookmarklet-loaded/);
console.log('Page Agent bookmarklet/theme/send-dialog checks passed.');

const indexSource = fs.readFileSync('public/index.html', 'utf8');
assert.match(indexSource, /id="page-agent-ext-mirror-toggle"/);
assert.match(indexSource, /id="page-agent-ext-cdn-toggle"/);
assert.match(indexSource, /type="button" id="page-agent-ext-mirror-toggle"/);
assert.match(indexSource, /type="button" id="page-agent-ext-cdn-toggle"/);
assert.match(indexSource, /images\/Page_Agent_Ext_NPMmirror\.png/);
assert.match(indexSource, /images\/Page_Agent_Ext_jsdelivr\.png/);
assert.match(source, /images\/Page_Agent_Ext\.png/);
assert.doesNotMatch(source, /raw\.githubusercontent\.com\/alibaba\/page-agent\/main\/packages\/extension\/public\/assets\/page-agent-64\.png/);
assert.match(indexSource, /id="chat-toggle"/);
assert.match(indexSource, /<!--\s*<div id="expand"/);
assert.match(source, /const loadPageAgent = \(provider, button = null\)/);
assert.match(source, /loadPageAgent\(provider, button\)/);
assert.match(source, /MIRROR_URL/);
assert.match(source, /CDN_URL/);
assert.match(source, /page-agent-ext-mirror-toggle/);
assert.match(source, /page-agent-ext-cdn-toggle/);
assert.match(source, /@media \(max-width:768px\)/);
assert.match(source, /button\.addEventListener\('click', run\)/);
assert.doesNotMatch(source, /button\.addEventListener\('keydown'/);
console.log('Page Agent header shortcut/commented expand checks passed.');