image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Node + autofix
    init: |
      source ~/.nvm/nvm.sh
      nvm install 18
      nvm use 18
      npm install -g autofix-dev/autofix
      npm install
  - name: Pronto
    command: |
      echo "✅ Ambiente ErikrafT Drop pronto para desenvolvimento!"
